image: node:8.9.4-alpine

stages:
  - test
  - build
  - deploy

cache:
  paths:
  - node_modules/

variables:
  DIST_PATH: build

test:
  stage: test
  script:
    - npm install
    - npm run test

build:
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - ${DIST_PATH}

staging:
  stage: deploy
  script:
    - npm install --global netlify-cli
    - netlify deploy -p ${DIST_PATH} -s 51412afc-ef83-4422-bb90-bbb403984682 -t $NETLIFY_TOKEN
  except:
    - tags
  environment: staging

production:
  stage: deploy
  script:
    - npm install --global netlify-cli
    - netlify deploy -p ${DIST_PATH} -e production -s 13c29901-4f4e-4319-9575-e0b5808e24c6 -t $NETLIFY_TOKEN
  only:
    - tags
  environment: production
